spring:
  profiles:
    #加载当前项目所依赖的jar项目中application-xxx.xml，通过xxx名称进行加载
    active: mapper

dubbo:
  application:
    name: ego-provider
  registry:
    #    zookeeper地址
    address: zookeeper://127.0.0.1:2181
